apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-model
  namespace: ai-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-model
  template:
    metadata:
      labels:
        app: ai-model
    spec: 
      containers:
        - name: ai-model
          image: thanh8804/faster-whisper-small:latest
          ports:
            - containerPort: 8000  
          resources:
            requests:
              cpu: "1300m"
              memory: "3Mi"
            limits:
              cpu: "1400m"
              memory: "5Gi" 
