
apiVersion: v1
kind: Service
metadata:
  name: ai-model-service
  namespace: ai-model
spec:
  type: NodePort
  selector:
    app: ai-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30090
